# Generated by Django 3.0.5 on 2020-04-24 21:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0006_subscribe'),
    ]

    operations = [
      
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
